### ISSUE TITLE
Embedding style

### ISSUE THREAD

**Issue by TheLastProject** [GeorgeSG/lovelace-time-picker-card#10]
Thanks for the card! I really like it a lot.

### Problem
When putting the card inside another card, like an entities card, the padding is a bit much:

![image](https://user-images.githubusercontent.com/1885159/94197821-99705400-feb6-11ea-9c8c-79db022baaec.png)

### Suggested feature / solution
It would be nice to be able to have a setting to make the card use less padding and no box shadow to fit in more in the middle of other entities.

### Additional context
I have manually edited the CSS to:

- Remove the 16px padding from `.time-picker-row`
- Set `box-shadow: none` on `<ha-card class="type-custom-time-picker-card">`

That makes it look like this:
![image](https://user-images.githubusercontent.com/1885159/94198069-f8ce6400-feb6-11ea-8eaa-b80af9ca264a.png)

Which is already a huge improvement imho.

**Comment by GeorgeSG** [comment]
Thanks for the suggestion! I implemented this as an optional config in [version 1.1.0](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.1.0). See the release notes for more information. 🎉
