### ISSUE TITLE
Modding styles with card-mod

### ISSUE THREAD

**Issue by ukmgranger** [GeorgeSG/lovelace-time-picker-card#11]
I'm trying to mod the styles of this card with lovelace-card-mod, but I don't seem to be able to target the time-unit elements.

I have tried adding this to the card in lovelace, but it's not changing the cards CSS:

type: 'custom:time-picker-card'
entity: input_datetime.alarmclock_time
hour_step: 1
minute_step: 5
name: ''
layout:
  name: header
  align_controls: center
  hour_mode: double
hour_mode: 24
link_values: false
hide:
  name: false
style: |
  ha-card{
    border:solid 5px blue !important;
  }
  .time-unit{
    font-weight: 900 !important;
    border:solid 5px green !important;
  }

**Comment by ukmgranger** [comment]
As a note - I have managed to achieve the look I was after by altering the CSS in the JSON file.

**Comment by GeorgeSG** [comment]
Hi, I'm closing this issue since it looks like you've got it figured out.

In case anyone stumbles on the same problem, there are some examples of people customizing the styles in the [Home Assistant Community forum](https://community.home-assistant.io/t/lovelace-time-picker-card/193327/63).
