### ISSUE TITLE
Add input_boolean toggle option

### ISSUE THREAD

**Issue by SanderHestvik** [GeorgeSG/lovelace-time-picker-card#15]
### Problem
When using this to set my wake up alarm time it would be nice to have an option to toggle the alarm on and off

### Suggested feature / solution
Option to add an input_boolean toggle to the card in order to toggle automations related to the selected time

**Comment by GeorgeSG** [comment]
Thank you for the suggestion!

This is currently outside the scope of Time Picker Card. I'm trying to keep the functionality focused to a single entity - the `input_datetime` the users provide.

Adding control of a second Home Assistant entity will increase the complexity and open the flood gates for a lot of other custom features. So with that in mind, I'm closing this FR for now. If we drop the "single-entity" principle in the future, we'll revisit this.

**Comment by MacDada** [comment]
yeah, i'm looking for the same thing

right now i'm using Horizontal Stack Card with Entities on the left to have the switch - unfortunately it looks… hmm… bad :P

![Screenshot 2023-12-08 at 16 44 26](https://github.com/GeorgeSG/lovelace-time-picker-card/assets/136261/54569fc2-c3e0-4df0-bf5d-a04af57b8fc5)
