### ISSUE TITLE
Time values not showing

### ISSUE THREAD

**Issue by Mermyx** [GeorgeSG/lovelace-time-picker-card#22]
On the mobile companion app (ios) for home assistant, the numbers for the time picker do now show up, however when the arrows are tapped the time does change.
![8FCE3C58-F242-4ECA-BCCB-1BF25DB5754E](https://user-images.githubusercontent.com/62225333/126688641-ad4f8eb9-f7f1-4fb8-b53d-6bf1de22120d.png)

**Comment by GeorgeSG** [comment]
@Mermyx this looks like a theming issue.

Can you provide:
- your Home Assistant version
- the theme used in this screenshot 
- your iOS app companion version

I assume you are using the latest version of Time Picker Card?

Thank you

**Comment by Mermyx** [comment]
It was a theme issue, after changing the theme it all works

thank you
