### ISSUE TITLE
Maintain left and right padding when embedded

### ISSUE THREAD

**Issue by tungmeister** [GeorgeSG/lovelace-time-picker-card#24]
Hi, I'm wanting to use `embedded: true` to reduce the vertical padding between multiple instances of the card however when enabled the left and right padding is also lost making the start of the card misaligned with other cards in the view:
![image](https://user-images.githubusercontent.com/127809/130348794-892d5900-5257-46cf-bed4-e202abac8d4c.png)
I had a look at the code and tried adding padding values to:
```
      .time-picker-row.embedded {
        padding: 0px 16px 16px;
      }
```
but that made no difference. My JS knowledge is very limited but if you could point me to what I need to tweak I'll adjust it myself.

EDIT: looks like it was just my browser cache misbehaving. This change is doing as I wanted.

**Comment by MPowerData** [comment]
Is the solution to this below setting?

.time-picker-row.embedded {
        padding: 0px 16px 16px;
      }

Because this does not appear to be working for me, even after clearing cache.

**Comment by tungmeister** [comment]
> Is the solution to this below setting?
> 
> .time-picker-row.embedded { padding: 0px 16px 16px; }
> 
> Because this does not appear to be working for me, even after clearing cache.

did you delete the *.gz version of the card? If you don't that gets used instead so any changes you make to the *.js won't take effect.

**Comment by MPowerData** [comment]
> > Is the solution to this below setting?
> > .time-picker-row.embedded { padding: 0px 16px 16px; }
> > Because this does not appear to be working for me, even after clearing cache.
> 
> did you delete the *.gz version of the card? If you don't that gets used instead so any changes you make to the *.js won't take effect.

Ah, that indeed was needed. Thanks a lot.

I actually changed it to padding: 0px 16px 0px; for a more condensed look.

**Comment by GeorgeSG** [comment]
Hi,

If I understand correctly, you have 2 embedded cards - one with `embedded: true`, one without.

This is the expected default behavior:
- when you set `embedded: true` the card expects it's nested/embedded within another card and removes all padding to align with other components that may be around it.
- when the card does not have `embedded: true` it acts as if it's a standalone card.

Using `embedded: true` to reduce vertical padding is a cheat :) I see how it may be something people want though, I'll consider adding a separate option for that.

**Comment by GeorgeSG** [comment]
[Version 1.3.0](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.3.0) adds a `thin` option that should help.
