### ISSUE TITLE
Add last update as secondary info/line

### ISSUE THREAD

**Issue by GLLM** [GeorgeSG/lovelace-time-picker-card#25]
Hi 
Thanks for the nice card !

I'd love to be able to able to have a secondary info/line right below the title showing when the last update was made.

Thanks

**Comment by GeorgeSG** [comment]
Hi @GLLM ,

I don't think this is a standard behavior for any of the native Home Assistant cards, so I will not be implementing it as a native feature to Time Picker card.

You should be able to achieve this with some other card (for example [markdown](https://www.home-assistant.io/dashboards/markdown/)) below Time Picker card.
