### ISSUE TITLE
Just a little detail

### ISSUE THREAD

**Issue by elchanly** [GeorgeSG/lovelace-time-picker-card#3]
Please correct documentation. The right lines to write in resources.yaml are:
  - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
    type: module
not 
  - url: /local/time-picker-card.js
    type: module
Congrats for this plugin!!!!!

**Comment by GeorgeSG** [comment]
Thanks! I updated the README, hope it's more clear now!
