### ISSUE TITLE
Find out how the feature works : more info dialog

### ISSUE THREAD

**Issue by ullrik** [GeorgeSG/lovelace-time-picker-card#42]
Hello,

First, Thanks for the work.
I wanted to know how I can do to keep the operation to have the popup "more info dialog" ? 

Cordially

**Comment by GeorgeSG** [comment]
Hi @ullrik,

Thanks for the suggestion. This feature wlll come in the next version of Time Picker card!

**Comment by GeorgeSG** [comment]
[Version 1.3.0](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.3.0) adds an option to define tap actions. It will default to `more-info`.

**Comment by ullrik** [comment]
Thanks, I will try :)
