### ISSUE TITLE
Hide icon not working in companion

### ISSUE THREAD

**Issue by jymorel** [GeorgeSG/lovelace-time-picker-card#45]
Hello,
it seems that the hide icon setting is not working in the companion app ? Impossible to hide it in companion ?
It works well on computer ... 
Thanks
![card_code](https://user-images.githubusercontent.com/96637729/201382146-1c77b94a-54d6-46e0-a75f-16f4f8c3f470.jpg)
![companion](https://user-images.githubusercontent.com/96637729/201382149-1c1237a3-15bf-4ddf-bdd7-775aa243fdb9.jpg)
![UI computer](https://user-images.githubusercontent.com/96637729/201382152-e7f7123e-bef3-4af9-b4a9-93c8b2247634.jpg)

**Comment by GeorgeSG** [comment]
Hi, if the editor is showing the card without the icon and then the dashboard on the mobile app is showing it with the icon, I think this is a caching issue.

@jymorel  Can you clear the App's cache and try again? Thanks

**Comment by jymorel** [comment]
You are right. It was the cache ... Thank you for your help
