### ISSUE TITLE
Dynamic Hours when using Minutes Picker

### ISSUE THREAD

**Issue by jeremywillans** [GeorgeSG/lovelace-time-picker-card#5]
Firstly.. awesome card !! Makes a great addition to my setup 🥳 

### Problem

When navigating with the minutes picker, the hour remains fixed.

Is it possible to make this more dynamic ? This will help to improve WAF

### Suggested feature / solution

If the current time is 05:00, pressing the minutes down arrow should change to 04:55, rather than 05:55

**Comment by GeorgeSG** [comment]
@jeremywillans thanks for the suggestion!

I added this in version [1.0.1](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.0.1). There is an optional `link_values` config, which if set to `true`, will change the behavior to what you're describing.

Let me know if there are any issues with that :)

**Comment by jeremywillans** [comment]
Works a treat! Thanks :)
