### ISSUE TITLE
Change the font

### ISSUE THREAD

**Issue by Gavergracht** [GeorgeSG/lovelace-time-picker-card#53]
How can I change the font so it is the same of the theme font ?

![image](https://github.com/GeorgeSG/lovelace-time-picker-card/assets/38202514/e863affd-df5c-4a29-9025-6a198fea5c3b)

**Comment by GeorgeSG** [comment]
Sorry for the late response :) Not sure how you used the card, but I can't reproduce this in the latest version of Home Assistant. The card uses the default font-family
