### ISSUE TITLE
Specifying color, a little help?

### ISSUE THREAD

**Issue by MaxVonEvil** [GeorgeSG/lovelace-time-picker-card#55]
Hi, I am not sure how to define time-picker-elements-background-color in the yaml? I have not found an example for this.

Does it go under a theme header and what how is the rgb format specified, eg. 0xFF00FF or something?

Thank you

**Comment by GeorgeSG** [comment]
Sorry for the late response! You don't set the color in the yaml, you set it in the theme configuration. You need a custom theme for that. See [defining-themes](https://www.home-assistant.io/integrations/frontend/#defining-themes)
