### ISSUE TITLE
Round edges when using header

### ISSUE THREAD

**Issue by OckertM** [GeorgeSG/lovelace-time-picker-card#6]
### Problem

When using layout>name as header the top corners are not rounded like the bottom corners when using a custom theme. When using Layout>name as inside all the corners are rounded like they should be according to the theme.
![Feature request](https://user-images.githubusercontent.com/20000599/84805342-63444e00-b004-11ea-80ee-0cd589f561e8.png)

### Suggested feature / solution

Make the header bar reference corner rounding from themes. 

Thanks for making an EPIC card!!

**Comment by GeorgeSG** [comment]
@OckertM thanks for opening the issue and for the nice words!

I added border-radius in version [1.0.1](https://github.com/GeorgeSG/lovelace-time-picker-card/releases/tag/1.0.1). You can customize it by setting the `time-picker-border-radius` theme variable, but it should get the default border radius from your theme.
