### ISSUE TITLE
Horizontal stack

### ISSUE THREAD

**Issue by pricard32** [GeorgeSG/lovelace-time-picker-card#9]
Would like to be able to add multiple controls on the same card.

**Comment by GeorgeSG** [comment]
Thanks for the suggestion, @pricard32! I think you should be able to do that with HomeAssistant's Vertical Stack card or the custom [vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card). I'd suggest trying them and let me know if there's something you can't achieve using one of them :)
